steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamsync:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/streamsync:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_DEP_ENV'
      - '--image'
      - 'gcr.io/$PROJECT_ID/streamsync:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      # Set the HOST_DOMAIN environment variable used by frontend
      - '--set-env-vars=GCS_BUCKET_NAME=$_GCS_BUCKET_NAME'
      - '--update-secrets=GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest'
      - 'HOST_DOMAIN=streamsync.arayalogic.ai'

images:
  - 'gcr.io/$PROJECT_ID/streamsync:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
